Traceback (most recent call last):
  File "C:\Users\rafas\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\rafas\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\rafas\AppData\Local\Programs\Python\Python310\Scripts\uvicorn.exe\__main__.py", line 7, in <module>
    sys.exit(main())
  File "C:\Users\rafas\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1161, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\rafas\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1082, in main
    rv = self.invoke(ctx)
  File "C:\Users\rafas\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1443, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\rafas\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 788, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\rafas\AppData\Local\Programs\Python\Python310\lib\site-packages\uvicorn\main.py", line 425, in main
    run(app, **kwargs)
  File "C:\Users\rafas\AppData\Local\Programs\Python\Python310\lib\site-packages\uvicorn\main.py", line 447, in run
    server.run()
  File "C:\Users\rafas\AppData\Local\Programs\Python\Python310\lib\site-packages\uvicorn\server.py", line 68, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\rafas\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\rafas\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 641, in run_until_complete
    return future.result()
  File "C:\Users\rafas\AppData\Local\Programs\Python\Python310\lib\site-packages\uvicorn\server.py", line 76, in serve
    config.load()
  File "C:\Users\rafas\AppData\Local\Programs\Python\Python310\lib\site-packages\uvicorn\config.py", line 448, in load
    self.loaded_app = import_from_string(self.app)
  File "C:\Users\rafas\AppData\Local\Programs\Python\Python310\lib\site-packages\uvicorn\importer.py", line 24, in import_from_string
    raise exc from None
  File "C:\Users\rafas\AppData\Local\Programs\Python\Python310\lib\site-packages\uvicorn\importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "C:\Users\rafas\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\rafas\Desktop\Ing_software\4ºaño\1erSemestre\ing_web\exámenes\vendaval\backend\.\main.py", line 2, in <module>
    from routers import articulos_router, pujas_router
  File "C:\Users\rafas\Desktop\Ing_software\4ºaño\1erSemestre\ing_web\exámenes\vendaval\backend\.\routers\articulos_router.py", line 3, in <module>
    from db_connection import get_database
  File "C:\Users\rafas\Desktop\Ing_software\4ºaño\1erSemestre\ing_web\exámenes\vendaval\backend\.\db_connection.py", line 3, in <module>
    from dotenv import load_dotenv
ModuleNotFoundError: No module named 'dotenv'
